### ISSUE TITLE
Shader compilation fails

### ISSUE THREAD

**Issue by N8n5h** [armory3d/voxel_world#8]
Compilation of the shaders fails on this line: https://github.com/armory3d/voxel_world/blob/7f51785388bf27e74ad501d36db658cdf88a0569/Shaders/vox.frag.glsl#L30

with ERROR: /.../vox.frag.glsl:30: 'packFloatInt16' : no matching overloaded function found.

**Comment by onelsonic** [comment]
same here impossible to compile the file on any SDK.
I have the following same error :

	ERROR: C:\voxel\build_voxels\compiled\Shaders\Project\vox.frag.glsl:30: 'packFloatInt16' : no matching overloaded function found
	ERROR: C:\voxel\build_voxels\compiled\Shaders\Project\vox.frag.glsl:30: '' : missing #endif
	ERROR: C:\voxel\build_voxels\compiled\Shaders\Project\vox.frag.glsl:30: '' : compilation terminated
	ERROR: 3 compilation errors.  No code generated.


	SPIR-V is not generated for failed compile or link

	Compiling shader 3 of 4 (vox.frag.glsl) failed:
	Shader compiler error.
	(node:14472) UnhandledPromiseRejectionWarning: Shader compiler error.
	(node:14472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
	(node:14472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
	Build failed, check console

**Comment by luboslenco** [comment]
Compilation errors are fixed but Krom executable in ArmorySDK needs to be updated, will take care of that.

**Comment by onelsonic** [comment]
I tested it with the august SDK 1908 it works.
Thank you
and yes the September SDK has some Krom issues
